[net]
git-fetch-with-cli = true

[patch.crates-io]
greentic-types = { git = "https://github.com/greentic-ai-org/greentic-types", branch = "develop" }
greentic-interfaces = { git = "https://github.com/greentic-ai-org/greentic-interfaces", branch = "develop" }
